; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.28"

; Modules
projects[views_bulk_operations][version] = "3.2"

projects[admin_menu][version] = "3.0-rc4"

projects[advanced_forum][version] = "2.3"

projects[ajax_links_api][version] = "1.83"

projects[betterlogin][version] = "1.2"

projects[boost][version] = "1.0"

projects[ctools][version] = "1.4"

projects[ckeditor][version] = "1.13"

projects[complete_profile][subdir] = "patched"
projects[complete_profile][version] = "1.0-rc1"

projects[content_taxonomy][version] = "1.0-beta2"

projects[custom_search][version] = "1.16"

projects[date][version] = "2.7"

projects[delete_all][version] = "1.1"

projects[demo][version] = "1.0"

projects[elements][version] = "1.4"

projects[entity][version] = "1.5"

projects[entitycache][version] = "1.2"

projects[entityreference][version] = "1.1"

projects[expire][version] = "2.0-rc3"

projects[features][version] = "1.0"

projects[feed_import][version] = "2.7"

projects[feeds][version] = "2.0-alpha8"

projects[feeds_tamper][version] = "1.0-beta5"

projects[fivestar][version] = "2.1"

projects[flag][subdir] = "mods"
projects[flag][version] = "2.2"

projects[globalredirect][version] = "1.5"

projects[google_analytics][version] = "1.4"

projects[html5_tools][version] = "1.2"

projects[hybridauth][version] = "2.8"

projects[imce][version] = "1.8"

projects[job_scheduler][version] = "2.0-alpha3"

projects[jquery_update][version] = "2.4"

projects[libraries][version] = "2.2"

projects[link][version] = "1.2"

projects[mail_edit][version] = "1.0"

projects[maillog][version] = "1.x-dev"

projects[menu_token][version] = "1.0-beta5"

projects[metatags_quick][version] = "2.7"

projects[modal_forms][version] = "1.2"

projects[mollom][version] = "2.9"

projects[multiupload_filefield_widget][version] = "1.13"

projects[references][version] = "2.1"

projects[og][version] = "2.6"

projects[og_extras][version] = "1.1"

projects[parallax_bg][version] = "1.2"

projects[pathauto][version] = "1.2"

projects[prepopulate][version] = "2.x-dev"

projects[profile2][subdir] = "patched"
projects[profile2][version] = "1.3"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[quick_tabs][download][type] = ""
projects[quick_tabs][download][url] = ""
projects[quick_tabs][type] = "module"
projects[quick_tabs][subdir] = "realquestions"
projects[quick_tabs][version] = "0.5"

projects[quicktabs][version] = "3.6"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[rqviews][download][type] = ""
projects[rqviews][download][url] = ""
projects[rqviews][type] = "module"
projects[rqviews][subdir] = "realquestions"
projects[rqviews][version] = "1.0-beta2"

projects[rules][version] = "2.6"

projects[shield][version] = "1.2"

projects[subscriptions][version] = "1.1"

projects[taxonomy_autocomplete_settings][version] = "1.0"

projects[taxonomy_filter][version] = "1.x-dev"

projects[tb_megamenu][version] = "1.0-beta2"

projects[tf_views][version] = "1.x-dev"

projects[token][version] = "1.5"

projects[variable][version] = "2.4"

projects[views][version] = "3.7"

projects[views_bootstrap][version] = "3.0"

projects[views_calc][version] = "1.1"

projects[views_data_export][version] = "3.0-beta7"

projects[views_slideshow][version] = "3.1"

projects[votingapi][version] = "2.11"

projects[webform][version] = "3.20"

projects[widgets][version] = "1.0-rc1"

projects[workbench][version] = "1.2"

projects[workbench_moderation][version] = "1.3"

; Themes
projects[bootstrap][version] = "3.0"

