; This file was auto-generated by drush make
core = 7.x

api = 2

; Modules
projects[] = admin_menu

projects[] = advanced_forum

projects[] = betterlogin

;projects[] = ctools

projects[] = ckeditor

projects[] = complete_profile

projects[] = content_taxonomy

projects[] = date

projects[] = elements

projects[] = entity

projects[] = entityreference

;projects[] = features

projects[] = feed_import

projects[feeds][version] = "2.0-alpha8"

projects[] = feeds_tamper

projects[] = fivestar

projects[] = flag

projects[] = globalredirect

projects[] = imce

projects[job_scheduler][version] = "2.0-alpha3"

projects[] = jquery_update

projects[] =libraries

projects[] = mail_edit

projects[] = maillog

projects[menu_token][version] = "1.0-beta5"

projects[] = metatags_quick

projects[] = multiupload_filefield_widget

projects[] = references

projects[] = pathauto

projects[] = prepopulate

projects[] = quicktabs

projects[] = services

projects[] = rules

;projects[] = token

projects[] = votingapi

projects[] = profile2

;projects[services_search][version] = "3.0+2-dev"

projects[] = state_machine

projects[] = subscriptions

projects[] = taxonomy_autocomplete_settings

projects[taxonomy_filter][version] = "1.x-dev"

projects[] = token

;projects[] = views

projects[] = views_bootstrap

projects[views_data_export][version] = "3.0-beta7"

projects[views_datasource][version] = "1.x-dev"



; Themes
projects[] = bootstrap

