<footer>
<div class="footer container centered">

	<div class="row clearfix">
		<div class="social-icons social-media-icons col-sm-12 col-lg-12 offset2 column">
			<a href="https://plus.google.com/108816489598835870606"><img src="<?php print $GLOBALS['base_url'] . "/". drupal_get_path('theme', 'realquestions'); ?>/icons/gplus-sm.png" /></a>
			<a href="https://www.facebook.com/RealQuestionsAustralia"><img src="<?php print $GLOBALS['base_url'] . "/". drupal_get_path('theme', 'realquestions'); ?>/icons/facebook-sm.png" /></a>
		    <a href="https://www.linkedin.com/company/real-questions"><img src="<?php print $GLOBALS['base_url'] . "/". drupal_get_path('theme', 'realquestions'); ?>/icons/linkedin-sm.png" /></a>
		    <a href="https://www.youtube.com/user/realquestionsoz"><img src="<?php print $GLOBALS['base_url'] . "/". drupal_get_path('theme', 'realquestions'); ?>/icons/youtube-sm.png" /></a>
        </div>
    </div> 
   	<div class="col-sm-12 col-lg-12 offset2 column">
        <div class="region region-footer block-menu-menu-footer centered">
            <?php print render($page['footer']); ?>
        </div>
	</div>
</div>    
</footer>
